#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dapper.Linq2Sql
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="dbOgrenci")]
	public partial class lqDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertOgrenci(Ogrenci instance);
    partial void UpdateOgrenci(Ogrenci instance);
    partial void DeleteOgrenci(Ogrenci instance);
    #endregion
		
		public lqDataContext() : 
				base(global::Dapper.Properties.Settings.Default.dbOgrenciConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public lqDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public lqDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public lqDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public lqDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Ogrenci> Ogrencis
		{
			get
			{
				return this.GetTable<Ogrenci>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Ogrenci")]
	public partial class Ogrenci : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID_OGRENCI;
		
		private string _ADSOYAD;
		
		private string _ADRES;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnID_OGRENCIChanging(int value);
    partial void OnID_OGRENCIChanged();
    partial void OnADSOYADChanging(string value);
    partial void OnADSOYADChanged();
    partial void OnADRESChanging(string value);
    partial void OnADRESChanged();
    #endregion
		
		public Ogrenci()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_OGRENCI", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID_OGRENCI
		{
			get
			{
				return this._ID_OGRENCI;
			}
			set
			{
				if ((this._ID_OGRENCI != value))
				{
					this.OnID_OGRENCIChanging(value);
					this.SendPropertyChanging();
					this._ID_OGRENCI = value;
					this.SendPropertyChanged("ID_OGRENCI");
					this.OnID_OGRENCIChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ADSOYAD", DbType="VarChar(75) NOT NULL", CanBeNull=false)]
		public string ADSOYAD
		{
			get
			{
				return this._ADSOYAD;
			}
			set
			{
				if ((this._ADSOYAD != value))
				{
					this.OnADSOYADChanging(value);
					this.SendPropertyChanging();
					this._ADSOYAD = value;
					this.SendPropertyChanged("ADSOYAD");
					this.OnADSOYADChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ADRES", DbType="VarChar(100)")]
		public string ADRES
		{
			get
			{
				return this._ADRES;
			}
			set
			{
				if ((this._ADRES != value))
				{
					this.OnADRESChanging(value);
					this.SendPropertyChanging();
					this._ADRES = value;
					this.SendPropertyChanged("ADRES");
					this.OnADRESChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
